version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: master
    schedule:
      interval: weekly
      day: friday
      time: "23:00"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore(actions)
    labels:
      - dependencies
    groups:
      actions-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /
    target-branch: master
    schedule:
      interval: weekly
      day: friday
      time: "23:00"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore(deps)
    labels:
      - dependencies
    groups:
      javascript-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: pip
    directory: /backend
    target-branch: master
    schedule:
      interval: weekly
      day: friday
      time: "23:00"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore(deps)
    labels:
      - dependencies
    groups:
      python-minor-patch:
        update-types:
          - minor
          - patch
