export const START_MARKER = "<!-- luckyseva-changelog:start -->";
export const END_MARKER = "<!-- luckyseva-changelog:end -->";

// The file header carries the newest entry date, so a reader can see how fresh the
// changelog is without scrolling to the first dated section.
const TITLE = "# Changelog";
const LAST_UPDATED_LINE = /^\*\*Last updated:\*\*.*$/m;

export type ChangelogKind = "added" | "changed" | "fixed";

export interface ChangelogEntry {
  pr_number: number;
  pr_title: string;
  pr_author: string | null;
  pr_url: string | null;
  kind: ChangelogKind;
  entry_date: string;
}

const KIND_HEADING: Record<ChangelogKind, string> = {
  added: "Added",
  changed: "Changed",
  fixed: "Fixed",
};

const KIND_ORDER: ChangelogKind[] = ["added", "changed", "fixed"];

// `feat:`/`fix:` style prefixes. Everything else — `refactor`, `perf`, `docs`,
// `chore`, `ci`, `test`, `build`, `style`, `revert` — is a change to existing
// behaviour, and a title with no prefix at all is treated the same way.
const KIND_BY_PREFIX: Record<string, ChangelogKind> = {
  feat: "added",
  feature: "added",
  fix: "fixed",
  bugfix: "fixed",
  hotfix: "fixed",
};

const CONVENTIONAL_PREFIX = /^([a-z]+)(\([^)]*\))?(!)?:\s*/i;
const MAX_TITLE_LENGTH = 160;

export function classifyTitle(title: string): ChangelogKind {
  const match = CONVENTIONAL_PREFIX.exec(title.trim());
  if (match === null) return "changed";
  return KIND_BY_PREFIX[match[1].toLowerCase()] ?? "changed";
}

export function stripPrefix(title: string): string {
  const match = CONVENTIONAL_PREFIX.exec(title.trim());
  const stripped = match === null ? title.trim() : title.trim().slice(match[0].length);
  return stripped.length > 0 ? stripped : title.trim();
}

// UTC, so the same webhook replayed tomorrow still lands under the day the PR
// was actually opened.
export function entryDateFrom(iso: string): string {
  const parsed = Date.parse(iso);
  if (Number.isNaN(parsed)) throw new Error(`unparseable timestamp: ${iso}`);
  return new Date(parsed).toISOString().slice(0, 10);
}

function collapse(text: string): string {
  return text.replace(/\s+/g, " ").trim();
}

// "share the AddressForm" reads badly as a changelog bullet; identifiers that
// already start with a capital are left alone.
function sentence(text: string): string {
  return /^[a-z]/.test(text) ? text[0].toUpperCase() + text.slice(1) : text;
}

function entryLine(entry: ChangelogEntry): string {
  const title = sentence(collapse(stripPrefix(entry.pr_title)));
  const text = title.length > MAX_TITLE_LENGTH
    ? `${title.slice(0, MAX_TITLE_LENGTH - 1).trimEnd()}…`
    : title;
  const label = entry.pr_url === null
    ? `#${entry.pr_number}`
    : `[#${entry.pr_number}](${entry.pr_url})`;
  const author = entry.pr_author === null || entry.pr_author === "" ? "" : ` — @${entry.pr_author}`;
  return `- ${label} ${text}${author}`;
}

export function renderBlock(entries: ChangelogEntry[]): string {
  const byDate = new Map<string, ChangelogEntry[]>();
  for (const entry of entries) {
    const bucket = byDate.get(entry.entry_date) ?? [];
    bucket.push(entry);
    byDate.set(entry.entry_date, bucket);
  }

  const dates = [...byDate.keys()].sort().reverse();
  const lines: string[] = [
    START_MARKER,
    "",
    "> Generated by the PR review bot from opened pull requests. Entries are added when a",
    "> PR is opened, so one may appear here for a PR that was later closed unmerged. The",
    "> hand-written sections below this block are never touched.",
    "",
  ];

  for (const date of dates) {
    lines.push(`## ${date}`, "");
    const bucket = byDate.get(date) ?? [];
    for (const kind of KIND_ORDER) {
      const matching = bucket
        .filter((entry) => entry.kind === kind)
        .sort((a, b) => a.pr_number - b.pr_number);
      if (matching.length === 0) continue;
      lines.push(`### ${KIND_HEADING[kind]}`, "");
      for (const entry of matching) lines.push(entryLine(entry));
      lines.push("");
    }
  }

  lines.push(END_MARKER);
  return lines.join("\n");
}

// `applyBlock` and `hasChanged` must agree on what the region looks like, so the
// marker guarantee is enforced in one place. Without it a block that lost its
// markers would be inserted again on every run and the file would grow forever.
function normalizeBlock(block: string): string {
  const trimmed = block.trim();
  if (trimmed.includes(START_MARKER) && trimmed.includes(END_MARKER)) return trimmed;
  return `${START_MARKER}\n\n${trimmed}\n\n${END_MARKER}`;
}

export function applyBlock(current: string, block: string): string {
  const normalized = normalizeBlock(block);
  const start = current.indexOf(START_MARKER);
  let head: string;
  let rest: string;

  if (start !== -1) {
    const end = current.indexOf(END_MARKER, start);
    head = current.slice(0, start);
    rest = current.slice(end === -1 ? current.length : end + END_MARKER.length);
  } else {
    // No markers yet: the block goes above the first `##` heading, which keeps
    // the title and its intro paragraph at the top and puts the generated
    // history directly above whatever the file already documents.
    const firstHeading = current.search(/^## /m);
    head = firstHeading === -1 ? current : current.slice(0, firstHeading);
    rest = firstHeading === -1 ? "" : current.slice(firstHeading);
  }

  // One blank line between the parts and a single trailing newline, so running
  // this again over its own output is a no-op.
  return `${
    [head.trimEnd(), normalized, rest.replace(/^\n+/, "").trimEnd()]
      .filter((part) => part !== "")
      .join("\n\n")
  }\n`;
}

export function hasChanged(current: string, block: string): boolean {
  if (!current.includes(START_MARKER)) return true;
  const start = current.indexOf(START_MARKER);
  const end = current.indexOf(END_MARKER, start);
  if (end === -1) return true;
  return current.slice(start, end + END_MARKER.length) !== normalizeBlock(block);
}

export function newestEntryDate(entries: ChangelogEntry[]): string | null {
  return entries.length === 0
    ? null
    : entries.reduce((newest, e) => (e.entry_date > newest ? e.entry_date : newest), entries[0].entry_date);
}

// Rewrites the header line in place, or inserts it directly under the title.
// Idempotent: running it over its own output changes nothing.
export function applyLastUpdated(content: string, date: string): string {
  const line = `**Last updated:** ${date}`;
  if (LAST_UPDATED_LINE.test(content)) return content.replace(LAST_UPDATED_LINE, line);
  const title = content.indexOf(TITLE);
  if (title === -1) return `${line}\n\n${content}`;
  const afterTitle = title + TITLE.length;
  return `${content.slice(0, afterTitle)}\n\n${line}${content.slice(afterTitle)}`;
}

export function emptyChangelog(): string {
  return [
    TITLE,
    "",
    "**Last updated:** no entries yet",
    "",
    "All notable changes to **LuckySeva** are documented in this file.",
    "",
    "The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),",
    "and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).",
    "",
    "## [Unreleased]",
    "",
  ].join("\n");
}
