import {
  applyBlock,
  type ChangelogEntry,
  classifyTitle,
  emptyChangelog,
  entryDateFrom,
  hasChanged,
  renderBlock,
} from "./changelog.ts";
import { ensureBranch, findOpenPrForBranch, openPr, readFile, writeFile } from "./github.ts";
import type { ChangelogOutcome, ReviewSettings } from "./types.ts";

export interface PullRequestEvent {
  number: number;
  title: string;
  html_url?: string;
  user?: { login?: string };
  created_at?: string;
  base?: { ref?: string; sha?: string };
}

export interface ChangelogStore {
  upsertEntry(entry: ChangelogEntry): Promise<void>;
  listEntries(repoFullName: string): Promise<ChangelogEntry[]>;
}

const PR_TITLE = "chore: update CHANGELOG";

function prBody(date: string, count: number): string {
  return [
    "Auto-generated by the PR review bot. One entry per opened pull request, grouped",
    "by the day it was opened.",
    "",
    `This run added ${count === 1 ? "1 entry" : `${count} entries`} dated ${date}.`,
    "",
    "Only the block between the `luckyseva-changelog` markers is machine-written —",
    "every hand-written section below it is preserved as-is. Close this PR if you would",
    "rather write the entry yourself; the next opened PR will reopen the work.",
    "",
    "Entries are written on **opened**, so this can list a PR that is later closed",
    "unmerged. Set `changelog_enabled = false` in `pr_review_settings` to turn it off.",
  ].join("\n");
}

function commitMessage(date: string, count: number): string {
  return `chore: update CHANGELOG (${date}, ${count} ${count === 1 ? "entry" : "entries"})`;
}

export async function recordChangelog(
  repo: string,
  pr: PullRequestEvent,
  settings: ReviewSettings,
  store: ChangelogStore,
  token: string,
): Promise<ChangelogOutcome> {
  if (!settings.changelogEnabled) {
    return { status: "disabled", prUrl: null, error: null };
  }

  const createdAt = pr.created_at ?? new Date().toISOString();
  const entry: ChangelogEntry = {
    pr_number: pr.number,
    pr_title: pr.title,
    pr_author: pr.user?.login ?? null,
    pr_url: pr.html_url ?? null,
    kind: classifyTitle(pr.title),
    entry_date: entryDateFrom(createdAt),
  };
  await store.upsertEntry(entry);

  const entries = await store.listEntries(repo);
  const block = renderBlock(entries);
  const base = pr.base?.ref ?? "master";
  const path = settings.changelogFile;

  const existing = await readFile(repo, path, settings.changelogBranch, token);
  if (existing !== null && !hasChanged(existing.content, block)) {
    return {
      status: "unchanged",
      prUrl: (await findOpenPrForBranch(repo, settings.changelogBranch, token))?.html_url ?? null,
      error: null,
    };
  }

  const current = existing?.content ?? emptyChangelog();
  const updated = applyBlock(current, block);
  const fromSha = pr.base?.sha ?? "";
  if (fromSha !== "") {
    await ensureBranch(repo, settings.changelogBranch, fromSha, token);
  }

  const added = entries.filter((row) => row.entry_date === entry.entry_date).length;
  await writeFile(
    repo,
    path,
    updated,
    commitMessage(entry.entry_date, added),
    settings.changelogBranch,
    existing?.sha ?? null,
    token,
  );

  const open = await findOpenPrForBranch(repo, settings.changelogBranch, token);
  if (open !== null) return { status: "ok", prUrl: open.html_url, error: null };

  const created = await openPr(
    repo,
    settings.changelogBranch,
    base,
    PR_TITLE,
    prBody(entry.entry_date, added),
    token,
  );
  return { status: "ok", prUrl: created.html_url, error: null };
}
